#!/usr/bin/env bash 
# Installs and setup haproxy 

apt-get -y update 
apt-get install -y haproxy


sudo sh -c 'echo " 
frontend http 
    bind *:80 
    mode http 
    default_backend web-backend 

backend web-backend 
    balance roundrobin 
    server 308081-web-01 34.224.4.113:80 check 
    server 308081-web-02 52.23.177.205:80 check 
" >> /etc/haproxy/haproxy.cfg'

sudo service haproxy restart
