#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid
# terminates itself when receiving a SIGQUIT or SIGTERM signal

echo "$$" > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm  /var/run/myscript.pid' 15
trap 'echo Y U no love me?!'
trap 'rm  /var/run/myscript.pid' 3

for ((;;))
do
	echo "To inifinity and beyond"
	sleep 2
done
