#!/usr/bin/env bash
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0
min=1

while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	while [ $min -le 59 ]
	do
		echo "$min"
		let min++
	done
	let min=1
        let hours++
done
