#!/usr/bin/env bash
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0

while [[ $hours -le 12 ]];
do
	echo "Hour: $hours"
	for i in {1..59};
	do
		echo "$i"
	done
        ((hours++))
done
~                                                                                                        ~      
