#!/usr/bin/env bash

file="school"

if [ -e $file ]
then
	echo "$file file exits"
	if [ -s "$file" ]
	then
		echo "$file file is empty"
	else
		echo "$file is not empy"
	fi

	if [ -f "$file" ]
	then
		echo "$file is a regular file"
	else
		echo "$file is not a regular file"
	fi

else
	echo "$file does not exist"
fi
